/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hongkailiu' at '21/01/17 1:12 PM' with Gradle 2.13
 *
 * @author hongkailiu, @date 21/01/17 1:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
